# Generated by Django 3.2.10 on 2021-12-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('player_photo', models.FileField(null=True, upload_to='media/photo/')),
                ('player_team', models.CharField(blank=True, max_length=500, null=True)),
                ('player_price', models.CharField(blank=True, max_length=500, null=True)),
                ('player_play_status', models.CharField(blank=True, max_length=500, null=True)),
                ('team_role', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
